# Generated by Django 5.1.15 on 2026-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('MARKETING', 'Agencia Digital & Marketing'), ('REAL_ESTATE', 'Agencia Inmobiliaria / Bienes Raíces'), ('TRAVEL', 'Agencia de Viajes & Turismo'), ('CONSULTING', 'Agencia de Consultoría & Servicios'), ('HEALTH_BEAUTY', 'Salud, Estética & Spa'), ('RETAIL_OTHER', 'Comercio & Servicios Generales')], default='MARKETING', max_length=30, verbose_name='Tipo de Agencia / Negocio'),
        ),
        migrations.AddField(
            model_name='business',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Módulos Habilitados'),
        ),
        migrations.AddField(
            model_name='business',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completado'),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_goal',
            field=models.CharField(default='Captar clientes y automatizar ventas', max_length=255, verbose_name='Objetivo Principal'),
        ),
        migrations.AlterField(
            model_name='business',
            name='branding_color',
            field=models.CharField(default='#881337', max_length=20, verbose_name='Color de Marca (Hex)'),
        ),
    ]
