# Generated by Django 5.1.15 on 2026-09-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_business_type_business_enabled_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='time_format',
            field=models.CharField(choices=[('12h', '12 Horas (ej: 09:00 AM / 09:00 PM)'), ('24h', '24 Horas (ej: 09:00 / 21:00)')], default='12h', max_length=10, verbose_name='Formato de Hora'),
        ),
    ]
