# Generated by Django 5.1.15 on 2026-09-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_time_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_editing_client_history',
            field=models.BooleanField(default=True, verbose_name='Permitir editar el historial de servicios de clientes'),
        ),
    ]
