# Generated by Django 5.1.15 on 2026-09-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_allow_editing_client_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sueldo Base ($)'),
        ),
    ]
