# Generated by Django 5.1.15 on 2026-09-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_staffmember_base_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación Google Maps / URL'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='staff_members_multi', to='business.branch', verbose_name='Sucursales Asignadas'),
        ),
    ]
