# Generated by Django 5.2.4 on 2026-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_branch_google_maps_url_staffmember_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='appointment_reminder_message',
            field=models.TextField(default='Hola {client_name}, te recordamos tu cita de *{service}* en *{business}* para el día *{date}* a las *{time}* con *{staff}*. ¡Te esperamos!', verbose_name='Plantilla de Recordatorio de Cita (WhatsApp)'),
        ),
    ]
