# Generated by Django 5.1.15 on 2026-10-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_appointment_reminder_message'),
        ('superadmin', '0006_region_regionpaymentmethod_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='superadmin.region', verbose_name='Región'),
        ),
    ]
