# Generated by Django 5.1.15 on 2026-10-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Banner/Portada'),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Negocio / Bio'),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de WhatsApp (Opcional)'),
        ),
    ]
