# Generated by Django 5.1.15 on 2026-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_business_banner_url_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff/profiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='business',
            name='banner_url',
            field=models.ImageField(blank=True, null=True, upload_to='business/banners/', verbose_name='Banner/Portada'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='business/logos/', verbose_name='Logo de Perfil'),
        ),
    ]
