# Generated by Django 5.1.15 on 2026-09-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_branch_google_maps_url_staffmember_branches'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='business.branch', verbose_name='Sucursal'),
        ),
    ]
