# Generated by Django 5.1.15 on 2026-09-16 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Código del Cupón')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento (%)')),
                ('valid_until', models.DateField(verbose_name='Válido Hasta')),
                ('max_uses', models.IntegerField(default=50, verbose_name='Usos Máximos')),
                ('uses_count', models.IntegerField(default=0, verbose_name='Usos Actuales')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='business.business')),
            ],
            options={
                'verbose_name': 'Cupón Promocional',
                'verbose_name_plural': 'Cupones Promocionales',
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Gift Card')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Actual')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcards', to='business.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards', to='crm.client')),
            ],
            options={
                'verbose_name': 'Gift Card / Tarjeta de Regalo',
                'verbose_name_plural': 'Gift Cards',
            },
        ),
    ]
