# Generated by Django 5.2.4 on 2026-10-07 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_appointment_reminder_message'),
        ('crm', '0003_alter_client_tax_id'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Campaña')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto del Email')),
                ('body', models.TextField(verbose_name='Contenido del Correo')),
                ('audience', models.CharField(choices=[('ALL', 'Todos los Clientes'), ('VIP', 'Clientes VIP / Frecuentes'), ('INACTIVE', 'Clientes Inactivos'), ('CUSTOM', 'Personalizado')], default='ALL', max_length=20, verbose_name='Audiencia Objetivo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Programa (Ej: Puntos Retail)')),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Puntos por cada $ gastado')),
                ('minimum_points_to_redeem', models.IntegerField(default=100, verbose_name='Puntos Mínimos para Canjear')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=0, verbose_name='Puntos Acumulados')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to='crm.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='marketing.loyaltyprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
