# Generated by Django 5.2.4 on 2026-10-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_emailcampaign_loyaltyprogram_loyaltycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre del Programa (Ej: Cliente VIP, Puntos Belleza)'),
        ),
    ]
