# Generated by Django 5.1.15 on 2026-09-22 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistoryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=200, verbose_name='Servicio / Tratamiento')),
                ('author', models.CharField(default='Staff', max_length=100)),
                ('content', models.TextField(verbose_name='Anotación Técnica / Detalle del Servicio')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_notes', to='agenda.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_notes', to='crm.client')),
            ],
            options={
                'verbose_name': 'Anotación de Servicio',
                'verbose_name_plural': 'Anotaciones de Servicios',
                'ordering': ['-created_at'],
            },
        ),
    ]
