# Generated by Django 5.1.15 on 2026-09-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_servicehistorynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI / Número de Identidad'),
        ),
    ]
