# Generated by Django 5.1.15 on 2026-09-20 19:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_business_business_type_business_enabled_modules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('code', models.CharField(choices=[('STARTER', 'Plan Inicial (Starter)'), ('PRO', 'Plan Profesional (Pro)'), ('ENTERPRISE', 'Plan Corporativo (Enterprise)')], max_length=50, unique=True, verbose_name='Código de Plan')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('29.00'), max_digits=10, verbose_name='Precio Mensual ($)')),
                ('annual_price', models.DecimalField(decimal_places=2, default=Decimal('290.00'), max_digits=10, verbose_name='Precio Anual ($)')),
                ('max_users', models.IntegerField(default=5, verbose_name='Límite de Usuarios')),
                ('max_branches', models.IntegerField(default=2, verbose_name='Límite de Sucursales')),
                ('included_modules', models.JSONField(blank=True, default=list, verbose_name='Módulos Incluidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan Activo')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_email', models.CharField(max_length=150, verbose_name='Usuario Ejecutor')),
                ('action', models.CharField(max_length=100, verbose_name='Acción Realizada')),
                ('details', models.TextField(verbose_name='Detalles de la Operación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría de Sistema',
                'verbose_name_plural': 'Registros de Auditoría de Sistema',
            },
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Licencia Activa'), ('TRIAL', 'En Período de Prueba'), ('EXPIRED', 'Licencia Vencida'), ('SUSPENDED', 'Cuenta Suspendida')], default='TRIAL', max_length=20, verbose_name='Estado de Licencia')),
                ('license_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Clave Token de Licencia')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('expiration_date', models.DateField(verbose_name='Fecha de Expiración')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación Automática')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas de Administración')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='business.business', verbose_name='Agencia / Negocio')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='superadmin.subscriptionplan', verbose_name='Plan Contratado')),
            ],
            options={
                'verbose_name': 'Suscripción de Agencia',
                'verbose_name_plural': 'Suscripciones de Agencias',
            },
        ),
    ]
