# Generated by Django 5.1.15 on 2026-09-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_on_landing',
            field=models.BooleanField(default=True, verbose_name='Mostrar en Landing Page / Index'),
        ),
    ]
