# Generated by Django 5.1.15 on 2026-09-26 19:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('superadmin', '0002_subscriptionplan_show_on_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellido')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Es Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este superadmin.', related_name='superadmin_user_set', related_query_name='superadmin_user', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este superadmin.', related_name='superadmin_user_permissions_set', related_query_name='superadmin_user', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'verbose_name': 'Super Administrador',
                'verbose_name_plural': 'Super Administradores',
                'db_table': 'superadmin_users',
            },
        ),
    ]
