# Generated by Django 5.1.15 on 2026-09-27 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_superadminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Método de Pago')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Identificador (ej: CASH, CARD, MERCADOPAGO)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción o Instrucciones Generales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Habilitado Globalmente')),
            ],
            options={
                'verbose_name': 'Método de Pago Global',
                'verbose_name_plural': 'Métodos de Pago Globales',
                'ordering': ['name'],
            },
        ),
    ]
