# Generated by Django 5.1.15 on 2026-09-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_globalpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='superadmin.subscriptionplan', verbose_name='Plan Solicitado (Pendiente Aprobar)'),
        ),
    ]
