# Generated by Django 5.1.15 on 2026-10-10 03:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_appointment_reminder_message'),
        ('superadmin', '0005_businesssubscription_pending_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Región')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código (ej: AR, CL, GLOBAL)')),
                ('currency_symbol', models.CharField(default='$', max_length=10, verbose_name='Símbolo de Moneda Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Región Activa')),
                ('is_default', models.BooleanField(default=False, verbose_name='Región por Defecto')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instrucciones para la Región (CBU, Alias, Link)')),
                ('use_for_sales', models.BooleanField(default=True, verbose_name='Usar en Ventas (POS) de las Agencias')),
                ('use_for_billing', models.BooleanField(default=False, verbose_name='Usar para Pagar Suscripción del SaaS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en esta Región')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_configurations', to='superadmin.globalpaymentmethod', verbose_name='Método de Pago Global')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='superadmin.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Método de Pago por Región',
                'verbose_name_plural': 'Métodos de Pago por Región',
                'unique_together': {('region', 'payment_method')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Informado')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='N° Referencia / Comprobante')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Pago Aprobado'), ('REJECTED', 'Pago Rechazado')], default='PENDING', max_length=20, verbose_name='Estado del Pago')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago Informada')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Administrador')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='business.business', verbose_name='Agencia')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.subscriptionplan', verbose_name='Plan Abonado')),
                ('region_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.regionpaymentmethod', verbose_name='Método de Pago Utilizado')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to='superadmin.superadminuser')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
