# Generated by Django 5.1.15 on 2026-10-10 03:32

from django.db import migrations


def create_default_region(apps, schema_editor):
    Region = apps.get_model('superadmin', 'Region')
    GlobalPaymentMethod = apps.get_model('superadmin', 'GlobalPaymentMethod')
    RegionPaymentMethod = apps.get_model('superadmin', 'RegionPaymentMethod')
    Business = apps.get_model('business', 'Business')

    # Create default region
    default_region, created = Region.objects.get_or_create(
        code='GLOBAL',
        defaults={
            'name': 'Global / Sin Región Específica',
            'currency_symbol': '$',
            'is_active': True,
            'is_default': True,
        }
    )

    # Assign all active global payment methods to this region
    active_methods = GlobalPaymentMethod.objects.filter(is_active=True)
    for method in active_methods:
        RegionPaymentMethod.objects.get_or_create(
            region=default_region,
            payment_method=method,
            defaults={
                'instructions': method.description,
                'use_for_sales': True,
                'use_for_billing': False,  # Default to false for billing
                'is_active': True,
            }
        )

    # Assign default region to all businesses that don't have one
    Business.objects.filter(region__isnull=True).update(region=default_region)


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_region_regionpaymentmethod_subscriptionpayment'),
        ('business', '0008_business_region'), # Need to depend on business migration to update Business model
    ]

    operations = [
        migrations.RunPython(create_default_region),
    ]
