# Generated by Django 5.1.15 on 2026-10-10 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_create_default_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje (soporta saltos de línea)')),
                ('type', models.CharField(choices=[('INFO', 'Informativo (Azul)'), ('WARNING', 'Advertencia (Amarillo)'), ('STRICT', 'Estricto/Bloqueo (Rojo)')], default='INFO', max_length=20, verbose_name='Tipo de Modal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='Se puede cerrar (X)')),
                ('action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto del Botón de Acción')),
                ('action_button_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL del Botón (ej: /negocio/configuracion/)')),
                ('target_missing_region', models.BooleanField(default=False, verbose_name='Solo para agencias SIN región asignada')),
                ('target_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.region', verbose_name='Filtrar por Región')),
            ],
            options={
                'verbose_name': 'Comunicado / Modal',
                'verbose_name_plural': 'Comunicados y Modales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_announcements', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='superadmin.systemannouncement')),
            ],
            options={
                'verbose_name': 'Descarte de Comunicado',
                'verbose_name_plural': 'Descartes de Comunicados',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
