# Generated by Django 5.1.15 on 2026-10-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_systemannouncement_announcementdismissal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemannouncement',
            name='target_region',
        ),
        migrations.AddField(
            model_name='systemannouncement',
            name='target_regions',
            field=models.ManyToManyField(blank=True, to='superadmin.region', verbose_name='Filtrar por Regiones'),
        ),
    ]
