# Generated by Django 5.1.15 on 2026-10-10 04:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_remove_systemannouncement_target_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRegionPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual Regional ($)')),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Anual Regional ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en esta Región')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_prices', to='superadmin.subscriptionplan', verbose_name='Plan')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_prices', to='superadmin.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Precio Regional de Plan',
                'verbose_name_plural': 'Precios Regionales de Planes',
                'unique_together': {('plan', 'region')},
            },
        ),
    ]
