# Generated by Django 5.1.15 on 2026-10-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_planregionpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country_codes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Códigos de País para Auto-detección (ej: AR, CL, UY)'),
        ),
    ]
