# Generated by Django 5.1.15 on 2026-09-16 20:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('WHATSAPP_REMINDER', 'Recordatorio de Cita por WhatsApp'), ('REACTIVATION_CAMPAIGN', 'Reactivación de Cliente Inactivo'), ('FINANCIAL_INSIGHT', 'Análisis Ejecutivo Financiero'), ('SMART_SLOT_SUGGESTION', 'Recomendación de Huecos de Agenda')], max_length=30)),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('response_generated', models.TextField()),
                ('status', models.CharField(default='SIMULATED', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
